# Generated by Django 6.0.3 on 2026-04-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=150, verbose_name='Nombre del solicitante')),
                ('documento_identidad', models.CharField(max_length=50, verbose_name='Documento de identidad')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono_contacto', models.BigIntegerField(verbose_name='Teléfono de contacto')),
                ('tipo_solicitud', models.CharField(choices=[('academica', 'Académica'), ('administrativa', 'Administrativa'), ('tecnica', 'Técnica'), ('otra', 'Otra')], max_length=20, verbose_name='Tipo de solicitud')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion_detallada', models.TextField(verbose_name='Descripción detallada')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de la solicitud')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='solicitudes/', verbose_name='Archivo adjunto')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
    ]
